### ISSUE TITLE
为什么clone失败啊

### ISSUE THREAD

**Issue by 812781385** [pdsuwwz/vite-pinia-starter#173]
wangrui@wangruideMac-Studio temp % git clone https://github.com/pdsuwwz/vite-pinia-starter.git
Cloning into 'vite-pinia-starter'...
remote: Enumerating objects: 8683, done.
remote: Counting objects: 100% (436/436), done.
remote: Compressing objects: 100% (135/135), done.
error: 7439 bytes of body are still expectediB | 268.00 KiB/s
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output

我切换飞机也是同样的

**Comment by pdsuwwz** [comment]
机场问题，换个机场或稍等再试
